// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.18.0
// source: greet-api/greet-api.proto

package greet_api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateGreetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: validate:"required"
	Dto *Greet `protobuf:"bytes,1,opt,name=dto,proto3" json:"dto,omitempty" validate:"required"`
}

func (x *CreateGreetRequest) Reset() {
	*x = CreateGreetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_greet_api_greet_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGreetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGreetRequest) ProtoMessage() {}

func (x *CreateGreetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_greet_api_greet_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGreetRequest.ProtoReflect.Descriptor instead.
func (*CreateGreetRequest) Descriptor() ([]byte, []int) {
	return file_greet_api_greet_api_proto_rawDescGZIP(), []int{0}
}

func (x *CreateGreetRequest) GetDto() *Greet {
	if x != nil {
		return x.Dto
	}
	return nil
}

type CreateGreetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   *Error `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *CreateGreetResponse) Reset() {
	*x = CreateGreetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_greet_api_greet_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGreetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGreetResponse) ProtoMessage() {}

func (x *CreateGreetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_greet_api_greet_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGreetResponse.ProtoReflect.Descriptor instead.
func (*CreateGreetResponse) Descriptor() ([]byte, []int) {
	return file_greet_api_greet_api_proto_rawDescGZIP(), []int{1}
}

func (x *CreateGreetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateGreetResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type GetGreetByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetGreetByIdRequest) Reset() {
	*x = GetGreetByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_greet_api_greet_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGreetByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGreetByIdRequest) ProtoMessage() {}

func (x *GetGreetByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_greet_api_greet_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGreetByIdRequest.ProtoReflect.Descriptor instead.
func (*GetGreetByIdRequest) Descriptor() ([]byte, []int) {
	return file_greet_api_greet_api_proto_rawDescGZIP(), []int{2}
}

func (x *GetGreetByIdRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetGreetByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Dto     *Greet `protobuf:"bytes,2,opt,name=dto,proto3" json:"dto,omitempty"`
	Error   *Error `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *GetGreetByIdResponse) Reset() {
	*x = GetGreetByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_greet_api_greet_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGreetByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGreetByIdResponse) ProtoMessage() {}

func (x *GetGreetByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_greet_api_greet_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGreetByIdResponse.ProtoReflect.Descriptor instead.
func (*GetGreetByIdResponse) Descriptor() ([]byte, []int) {
	return file_greet_api_greet_api_proto_rawDescGZIP(), []int{3}
}

func (x *GetGreetByIdResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetGreetByIdResponse) GetDto() *Greet {
	if x != nil {
		return x.Dto
	}
	return nil
}

func (x *GetGreetByIdResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type GetGreetListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: validate:"gte=0,lte=3"
	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty" validate:"gte=0,lte=3"`
	Lastid int32 `protobuf:"varint,2,opt,name=lastid,proto3" json:"lastid,omitempty"`
	// @inject_tag: validate:"gte=5,lte=20"
	Pagesize int32 `protobuf:"varint,3,opt,name=pagesize,proto3" json:"pagesize,omitempty" validate:"gte=5,lte=20"`
	Page     int32 `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *GetGreetListRequest) Reset() {
	*x = GetGreetListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_greet_api_greet_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGreetListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGreetListRequest) ProtoMessage() {}

func (x *GetGreetListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_greet_api_greet_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGreetListRequest.ProtoReflect.Descriptor instead.
func (*GetGreetListRequest) Descriptor() ([]byte, []int) {
	return file_greet_api_greet_api_proto_rawDescGZIP(), []int{4}
}

func (x *GetGreetListRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetGreetListRequest) GetLastid() int32 {
	if x != nil {
		return x.Lastid
	}
	return 0
}

func (x *GetGreetListRequest) GetPagesize() int32 {
	if x != nil {
		return x.Pagesize
	}
	return 0
}

func (x *GetGreetListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type GetGreetListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool       `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Data    *GreetList `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Error   *Error     `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *GetGreetListResponse) Reset() {
	*x = GetGreetListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_greet_api_greet_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGreetListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGreetListResponse) ProtoMessage() {}

func (x *GetGreetListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_greet_api_greet_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGreetListResponse.ProtoReflect.Descriptor instead.
func (*GetGreetListResponse) Descriptor() ([]byte, []int) {
	return file_greet_api_greet_api_proto_rawDescGZIP(), []int{5}
}

func (x *GetGreetListResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetGreetListResponse) GetData() *GreetList {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetGreetListResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type UpdateGreetStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status int32 `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *UpdateGreetStatusRequest) Reset() {
	*x = UpdateGreetStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_greet_api_greet_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateGreetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGreetStatusRequest) ProtoMessage() {}

func (x *UpdateGreetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_greet_api_greet_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGreetStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateGreetStatusRequest) Descriptor() ([]byte, []int) {
	return file_greet_api_greet_api_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateGreetStatusRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateGreetStatusRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type UpdateGreetStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   *Error `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *UpdateGreetStatusResponse) Reset() {
	*x = UpdateGreetStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_greet_api_greet_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateGreetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGreetStatusResponse) ProtoMessage() {}

func (x *UpdateGreetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_greet_api_greet_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGreetStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateGreetStatusResponse) Descriptor() ([]byte, []int) {
	return file_greet_api_greet_api_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateGreetStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateGreetStatusResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type UpdateGreetCountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Num    int32  `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	Column string `protobuf:"bytes,3,opt,name=column,proto3" json:"column,omitempty"`
}

func (x *UpdateGreetCountRequest) Reset() {
	*x = UpdateGreetCountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_greet_api_greet_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateGreetCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGreetCountRequest) ProtoMessage() {}

func (x *UpdateGreetCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_greet_api_greet_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGreetCountRequest.ProtoReflect.Descriptor instead.
func (*UpdateGreetCountRequest) Descriptor() ([]byte, []int) {
	return file_greet_api_greet_api_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateGreetCountRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateGreetCountRequest) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *UpdateGreetCountRequest) GetColumn() string {
	if x != nil {
		return x.Column
	}
	return ""
}

type UpdateGreetCountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   *Error `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *UpdateGreetCountResponse) Reset() {
	*x = UpdateGreetCountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_greet_api_greet_api_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateGreetCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGreetCountResponse) ProtoMessage() {}

func (x *UpdateGreetCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_greet_api_greet_api_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGreetCountResponse.ProtoReflect.Descriptor instead.
func (*UpdateGreetCountResponse) Descriptor() ([]byte, []int) {
	return file_greet_api_greet_api_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateGreetCountResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateGreetCountResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type DeleteGreetByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteGreetByIdRequest) Reset() {
	*x = DeleteGreetByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_greet_api_greet_api_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteGreetByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGreetByIdRequest) ProtoMessage() {}

func (x *DeleteGreetByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_greet_api_greet_api_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGreetByIdRequest.ProtoReflect.Descriptor instead.
func (*DeleteGreetByIdRequest) Descriptor() ([]byte, []int) {
	return file_greet_api_greet_api_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteGreetByIdRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteGreetByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   *Error `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *DeleteGreetByIdResponse) Reset() {
	*x = DeleteGreetByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_greet_api_greet_api_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteGreetByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGreetByIdResponse) ProtoMessage() {}

func (x *DeleteGreetByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_greet_api_greet_api_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGreetByIdResponse.ProtoReflect.Descriptor instead.
func (*DeleteGreetByIdResponse) Descriptor() ([]byte, []int) {
	return file_greet_api_greet_api_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteGreetByIdResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteGreetByIdResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type Greet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// @inject_tag: validate:"required,email"
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" validate:"required,email"`
	ViewNum int32  `protobuf:"varint,3,opt,name=view_num,json=viewNum,proto3" json:"view_num,omitempty"`
	// @inject_tag: validate:"gte=0,lte=3"
	Status         int32  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty" validate:"gte=0,lte=3"`
	CreateTime     int64  `protobuf:"varint,5,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	CreateDatetime string `protobuf:"bytes,6,opt,name=create_datetime,json=createDatetime,proto3" json:"create_datetime,omitempty"`
	UpdateDatetime string `protobuf:"bytes,7,opt,name=update_datetime,json=updateDatetime,proto3" json:"update_datetime,omitempty"`
}

func (x *Greet) Reset() {
	*x = Greet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_greet_api_greet_api_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Greet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Greet) ProtoMessage() {}

func (x *Greet) ProtoReflect() protoreflect.Message {
	mi := &file_greet_api_greet_api_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Greet.ProtoReflect.Descriptor instead.
func (*Greet) Descriptor() ([]byte, []int) {
	return file_greet_api_greet_api_proto_rawDescGZIP(), []int{12}
}

func (x *Greet) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Greet) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Greet) GetViewNum() int32 {
	if x != nil {
		return x.ViewNum
	}
	return 0
}

func (x *Greet) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Greet) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *Greet) GetCreateDatetime() string {
	if x != nil {
		return x.CreateDatetime
	}
	return ""
}

func (x *Greet) GetUpdateDatetime() string {
	if x != nil {
		return x.UpdateDatetime
	}
	return ""
}

type GreetList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total     int32    `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	TotalPage int32    `protobuf:"varint,2,opt,name=total_page,json=totalPage,proto3" json:"total_page,omitempty"`
	CurPage   int32    `protobuf:"varint,3,opt,name=cur_page,json=curPage,proto3" json:"cur_page,omitempty"`
	Datalist  []*Greet `protobuf:"bytes,4,rep,name=datalist,proto3" json:"datalist,omitempty"`
}

func (x *GreetList) Reset() {
	*x = GreetList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_greet_api_greet_api_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GreetList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetList) ProtoMessage() {}

func (x *GreetList) ProtoReflect() protoreflect.Message {
	mi := &file_greet_api_greet_api_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetList.ProtoReflect.Descriptor instead.
func (*GreetList) Descriptor() ([]byte, []int) {
	return file_greet_api_greet_api_proto_rawDescGZIP(), []int{13}
}

func (x *GreetList) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GreetList) GetTotalPage() int32 {
	if x != nil {
		return x.TotalPage
	}
	return 0
}

func (x *GreetList) GetCurPage() int32 {
	if x != nil {
		return x.CurPage
	}
	return 0
}

func (x *GreetList) GetDatalist() []*Greet {
	if x != nil {
		return x.Datalist
	}
	return nil
}

type GetGreetListByIdsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []int32 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
}

func (x *GetGreetListByIdsRequest) Reset() {
	*x = GetGreetListByIdsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_greet_api_greet_api_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGreetListByIdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGreetListByIdsRequest) ProtoMessage() {}

func (x *GetGreetListByIdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_greet_api_greet_api_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGreetListByIdsRequest.ProtoReflect.Descriptor instead.
func (*GetGreetListByIdsRequest) Descriptor() ([]byte, []int) {
	return file_greet_api_greet_api_proto_rawDescGZIP(), []int{14}
}

func (x *GetGreetListByIdsRequest) GetIds() []int32 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetGreetListByIdsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Data    []*Greet `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	Error   *Error   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *GetGreetListByIdsResponse) Reset() {
	*x = GetGreetListByIdsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_greet_api_greet_api_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGreetListByIdsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGreetListByIdsResponse) ProtoMessage() {}

func (x *GetGreetListByIdsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_greet_api_greet_api_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGreetListByIdsResponse.ProtoReflect.Descriptor instead.
func (*GetGreetListByIdsResponse) Descriptor() ([]byte, []int) {
	return file_greet_api_greet_api_proto_rawDescGZIP(), []int{15}
}

func (x *GetGreetListByIdsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetGreetListByIdsResponse) GetData() []*Greet {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetGreetListByIdsResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_greet_api_greet_api_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_greet_api_greet_api_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_greet_api_greet_api_proto_rawDescGZIP(), []int{16}
}

func (x *Error) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_greet_api_greet_api_proto protoreflect.FileDescriptor

var file_greet_api_greet_api_proto_rawDesc = []byte{
	0x0a, 0x19, 0x67, 0x72, 0x65, 0x65, 0x74, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x65, 0x65,
	0x74, 0x2d, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x67, 0x72, 0x65,
	0x65, 0x74, 0x5f, 0x61, 0x70, 0x69, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x38, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x72,
	0x65, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x03, 0x64, 0x74,
	0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x5f,
	0x61, 0x70, 0x69, 0x2e, 0x47, 0x72, 0x65, 0x65, 0x74, 0x52, 0x03, 0x64, 0x74, 0x6f, 0x22, 0x57,
	0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x72, 0x65, 0x65, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12,
	0x26, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x25, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x47, 0x72,
	0x65, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x7c,
	0x0a, 0x14, 0x47, 0x65, 0x74, 0x47, 0x72, 0x65, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x12, 0x22, 0x0a, 0x03, 0x64, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x67, 0x72, 0x65, 0x65, 0x74, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x72, 0x65, 0x65, 0x74, 0x52,
	0x03, 0x64, 0x74, 0x6f, 0x12, 0x26, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x5f, 0x61, 0x70, 0x69, 0x2e,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x75, 0x0a, 0x13,
	0x47, 0x65, 0x74, 0x47, 0x72, 0x65, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6c,
	0x61, 0x73, 0x74, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6c, 0x61, 0x73,
	0x74, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70,
	0x61, 0x67, 0x65, 0x22, 0x82, 0x01, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x47, 0x72, 0x65, 0x65, 0x74,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x28, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x5f, 0x61, 0x70, 0x69,
	0x2e, 0x47, 0x72, 0x65, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x12, 0x26, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x42, 0x0a, 0x18, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x47, 0x72, 0x65, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x5d, 0x0a, 0x19,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x72, 0x65, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x12, 0x26, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x53, 0x0a, 0x17, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x72, 0x65, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6c, 0x75,
	0x6d, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e,
	0x22, 0x5c, 0x0a, 0x18, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x72, 0x65, 0x65, 0x74, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x26, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x5f, 0x61, 0x70,
	0x69, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x28,
	0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x72, 0x65, 0x65, 0x74, 0x42, 0x79, 0x49,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x5b, 0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x47, 0x72, 0x65, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x26, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x67,
	0x72, 0x65, 0x65, 0x74, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0xd1, 0x01, 0x0a, 0x05, 0x47, 0x72, 0x65, 0x65, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x76, 0x69, 0x65, 0x77, 0x5f, 0x6e, 0x75, 0x6d, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x69, 0x65, 0x77, 0x4e, 0x75, 0x6d, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0e, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65,
	0x12, 0x27, 0x0a, 0x0f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x44, 0x61, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x89, 0x01, 0x0a, 0x09, 0x47, 0x72,
	0x65, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x1d, 0x0a,
	0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x61, 0x67, 0x65, 0x12, 0x19, 0x0a, 0x08,
	0x63, 0x75, 0x72, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x63, 0x75, 0x72, 0x50, 0x61, 0x67, 0x65, 0x12, 0x2c, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x61, 0x6c,
	0x69, 0x73, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x67, 0x72, 0x65, 0x65,
	0x74, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x72, 0x65, 0x65, 0x74, 0x52, 0x08, 0x64, 0x61, 0x74,
	0x61, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x2c, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x47, 0x72, 0x65, 0x65,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x79, 0x49, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x03,
	0x69, 0x64, 0x73, 0x22, 0x83, 0x01, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x47, 0x72, 0x65, 0x65, 0x74,
	0x4c, 0x69, 0x73, 0x74, 0x42, 0x79, 0x49, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x24, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x67, 0x72, 0x65, 0x65,
	0x74, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x72, 0x65, 0x65, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x12, 0x26, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x35, 0x0a, 0x05, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x32, 0xbc, 0x06, 0x0a, 0x0c, 0x47, 0x72, 0x65, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x69, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x72, 0x65, 0x65, 0x74,
	0x12, 0x1d, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x47, 0x72, 0x65, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1e, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x47, 0x72, 0x65, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x1b, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x15, 0x22, 0x10, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x72, 0x65,
	0x65, 0x74, 0x2f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x3a, 0x01, 0x2a, 0x12, 0x6b, 0x0a, 0x0c,
	0x47, 0x65, 0x74, 0x47, 0x72, 0x65, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x12, 0x1e, 0x2e, 0x67,
	0x72, 0x65, 0x65, 0x74, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x72, 0x65, 0x65,
	0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x67,
	0x72, 0x65, 0x65, 0x74, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x72, 0x65, 0x65,
	0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1a, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x14, 0x12, 0x12, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x72, 0x65, 0x65, 0x74,
	0x2f, 0x6f, 0x6e, 0x65, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x12, 0x70, 0x0a, 0x0c, 0x47, 0x65, 0x74,
	0x47, 0x72, 0x65, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1e, 0x2e, 0x67, 0x72, 0x65, 0x65,
	0x74, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x72, 0x65, 0x65, 0x74, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x67, 0x72, 0x65, 0x65,
	0x74, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x72, 0x65, 0x65, 0x74, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1f, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x19, 0x12, 0x17, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x72, 0x65, 0x65, 0x74, 0x2f, 0x6c, 0x69,
	0x73, 0x74, 0x2f, 0x7b, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x7d, 0x12, 0x7b, 0x0a, 0x11, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x72, 0x65, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x23, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x47, 0x72, 0x65, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x5f, 0x61, 0x70,
	0x69, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x72, 0x65, 0x65, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1b, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x15, 0x22, 0x10, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x72, 0x65, 0x65, 0x74, 0x2f, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x3a, 0x01, 0x2a, 0x12, 0x77, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x47, 0x72, 0x65, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x22, 0x2e, 0x67,
	0x72, 0x65, 0x65, 0x74, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47,
	0x72, 0x65, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x23, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x47, 0x72, 0x65, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1a, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x14, 0x22, 0x0f, 0x2f,
	0x76, 0x31, 0x2f, 0x67, 0x72, 0x65, 0x65, 0x74, 0x2f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x3a, 0x01,
	0x2a, 0x12, 0x72, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x72, 0x65, 0x65, 0x74,
	0x42, 0x79, 0x49, 0x64, 0x12, 0x21, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x5f, 0x61, 0x70, 0x69,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x72, 0x65, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x5f,
	0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x72, 0x65, 0x65, 0x74, 0x42,
	0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x18, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x12, 0x22, 0x0d, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x72, 0x65, 0x65, 0x74, 0x2f, 0x64,
	0x65, 0x6c, 0x3a, 0x01, 0x2a, 0x12, 0x78, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x47, 0x72, 0x65, 0x65,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x79, 0x49, 0x64, 0x73, 0x12, 0x23, 0x2e, 0x67, 0x72, 0x65,
	0x65, 0x74, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x72, 0x65, 0x65, 0x74, 0x4c,
	0x69, 0x73, 0x74, 0x42, 0x79, 0x49, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x24, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x47,
	0x72, 0x65, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x79, 0x49, 0x64, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x18, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x12, 0x22, 0x0d, 0x2f,
	0x76, 0x31, 0x2f, 0x67, 0x72, 0x65, 0x65, 0x74, 0x2f, 0x69, 0x64, 0x73, 0x3a, 0x01, 0x2a, 0x42,
	0x67, 0x5a, 0x3f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x6d,
	0x69, 0x6e, 0x64, 0x2d, 0x6c, 0x61, 0x62, 0x2f, 0x67, 0x72, 0x65, 0x65, 0x74, 0x2d, 0x61, 0x70,
	0x69, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67,
	0x72, 0x65, 0x65, 0x74, 0x2d, 0x61, 0x70, 0x69, 0x3b, 0x67, 0x72, 0x65, 0x65, 0x74, 0x5f, 0x61,
	0x70, 0x69, 0xca, 0x02, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5c, 0x47, 0x72, 0x65, 0x65, 0x74,
	0x2d, 0x61, 0x70, 0x69, 0xe2, 0x02, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5c, 0x47, 0x50, 0x42,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_greet_api_greet_api_proto_rawDescOnce sync.Once
	file_greet_api_greet_api_proto_rawDescData = file_greet_api_greet_api_proto_rawDesc
)

func file_greet_api_greet_api_proto_rawDescGZIP() []byte {
	file_greet_api_greet_api_proto_rawDescOnce.Do(func() {
		file_greet_api_greet_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_greet_api_greet_api_proto_rawDescData)
	})
	return file_greet_api_greet_api_proto_rawDescData
}

var file_greet_api_greet_api_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_greet_api_greet_api_proto_goTypes = []interface{}{
	(*CreateGreetRequest)(nil),        // 0: greet_api.CreateGreetRequest
	(*CreateGreetResponse)(nil),       // 1: greet_api.CreateGreetResponse
	(*GetGreetByIdRequest)(nil),       // 2: greet_api.GetGreetByIdRequest
	(*GetGreetByIdResponse)(nil),      // 3: greet_api.GetGreetByIdResponse
	(*GetGreetListRequest)(nil),       // 4: greet_api.GetGreetListRequest
	(*GetGreetListResponse)(nil),      // 5: greet_api.GetGreetListResponse
	(*UpdateGreetStatusRequest)(nil),  // 6: greet_api.UpdateGreetStatusRequest
	(*UpdateGreetStatusResponse)(nil), // 7: greet_api.UpdateGreetStatusResponse
	(*UpdateGreetCountRequest)(nil),   // 8: greet_api.UpdateGreetCountRequest
	(*UpdateGreetCountResponse)(nil),  // 9: greet_api.UpdateGreetCountResponse
	(*DeleteGreetByIdRequest)(nil),    // 10: greet_api.DeleteGreetByIdRequest
	(*DeleteGreetByIdResponse)(nil),   // 11: greet_api.DeleteGreetByIdResponse
	(*Greet)(nil),                     // 12: greet_api.Greet
	(*GreetList)(nil),                 // 13: greet_api.GreetList
	(*GetGreetListByIdsRequest)(nil),  // 14: greet_api.GetGreetListByIdsRequest
	(*GetGreetListByIdsResponse)(nil), // 15: greet_api.GetGreetListByIdsResponse
	(*Error)(nil),                     // 16: greet_api.Error
}
var file_greet_api_greet_api_proto_depIdxs = []int32{
	12, // 0: greet_api.CreateGreetRequest.dto:type_name -> greet_api.Greet
	16, // 1: greet_api.CreateGreetResponse.error:type_name -> greet_api.Error
	12, // 2: greet_api.GetGreetByIdResponse.dto:type_name -> greet_api.Greet
	16, // 3: greet_api.GetGreetByIdResponse.error:type_name -> greet_api.Error
	13, // 4: greet_api.GetGreetListResponse.data:type_name -> greet_api.GreetList
	16, // 5: greet_api.GetGreetListResponse.error:type_name -> greet_api.Error
	16, // 6: greet_api.UpdateGreetStatusResponse.error:type_name -> greet_api.Error
	16, // 7: greet_api.UpdateGreetCountResponse.error:type_name -> greet_api.Error
	16, // 8: greet_api.DeleteGreetByIdResponse.error:type_name -> greet_api.Error
	12, // 9: greet_api.GreetList.datalist:type_name -> greet_api.Greet
	12, // 10: greet_api.GetGreetListByIdsResponse.data:type_name -> greet_api.Greet
	16, // 11: greet_api.GetGreetListByIdsResponse.error:type_name -> greet_api.Error
	0,  // 12: greet_api.GreetService.CreateGreet:input_type -> greet_api.CreateGreetRequest
	2,  // 13: greet_api.GreetService.GetGreetById:input_type -> greet_api.GetGreetByIdRequest
	4,  // 14: greet_api.GreetService.GetGreetList:input_type -> greet_api.GetGreetListRequest
	6,  // 15: greet_api.GreetService.UpdateGreetStatus:input_type -> greet_api.UpdateGreetStatusRequest
	8,  // 16: greet_api.GreetService.UpdateGreetCount:input_type -> greet_api.UpdateGreetCountRequest
	10, // 17: greet_api.GreetService.DeleteGreetById:input_type -> greet_api.DeleteGreetByIdRequest
	14, // 18: greet_api.GreetService.GetGreetListByIds:input_type -> greet_api.GetGreetListByIdsRequest
	1,  // 19: greet_api.GreetService.CreateGreet:output_type -> greet_api.CreateGreetResponse
	3,  // 20: greet_api.GreetService.GetGreetById:output_type -> greet_api.GetGreetByIdResponse
	5,  // 21: greet_api.GreetService.GetGreetList:output_type -> greet_api.GetGreetListResponse
	7,  // 22: greet_api.GreetService.UpdateGreetStatus:output_type -> greet_api.UpdateGreetStatusResponse
	9,  // 23: greet_api.GreetService.UpdateGreetCount:output_type -> greet_api.UpdateGreetCountResponse
	11, // 24: greet_api.GreetService.DeleteGreetById:output_type -> greet_api.DeleteGreetByIdResponse
	15, // 25: greet_api.GreetService.GetGreetListByIds:output_type -> greet_api.GetGreetListByIdsResponse
	19, // [19:26] is the sub-list for method output_type
	12, // [12:19] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_greet_api_greet_api_proto_init() }
func file_greet_api_greet_api_proto_init() {
	if File_greet_api_greet_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_greet_api_greet_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateGreetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_greet_api_greet_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateGreetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_greet_api_greet_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGreetByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_greet_api_greet_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGreetByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_greet_api_greet_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGreetListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_greet_api_greet_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGreetListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_greet_api_greet_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateGreetStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_greet_api_greet_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateGreetStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_greet_api_greet_api_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateGreetCountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_greet_api_greet_api_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateGreetCountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_greet_api_greet_api_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteGreetByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_greet_api_greet_api_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteGreetByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_greet_api_greet_api_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Greet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_greet_api_greet_api_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GreetList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_greet_api_greet_api_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGreetListByIdsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_greet_api_greet_api_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGreetListByIdsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_greet_api_greet_api_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_greet_api_greet_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_greet_api_greet_api_proto_goTypes,
		DependencyIndexes: file_greet_api_greet_api_proto_depIdxs,
		MessageInfos:      file_greet_api_greet_api_proto_msgTypes,
	}.Build()
	File_greet_api_greet_api_proto = out.File
	file_greet_api_greet_api_proto_rawDesc = nil
	file_greet_api_greet_api_proto_goTypes = nil
	file_greet_api_greet_api_proto_depIdxs = nil
}
