// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: greeter-api.proto

package greeter_api

import (
	"github.com/imind-lab/micro/status"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateGreeterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: validate:"required"
	Data *Greeter `protobuf:"bytes,1,opt,name=data,proto3" json:"data" validate:"required"`
}

func (x *CreateGreeterRequest) Reset() {
	*x = CreateGreeterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_greeter_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGreeterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGreeterRequest) ProtoMessage() {}

func (x *CreateGreeterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_greeter_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGreeterRequest.ProtoReflect.Descriptor instead.
func (*CreateGreeterRequest) Descriptor() ([]byte, []int) {
	return file_greeter_api_proto_rawDescGZIP(), []int{0}
}

func (x *CreateGreeterRequest) GetData() *Greeter {
	if x != nil {
		return x.Data
	}
	return nil
}

// @inject_response CreateGreeterResponse
type CreateGreeterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
}

// @inject_response CreateGreeterResponse
func (x *CreateGreeterResponse) SetCode(code status.Code, message string) {
	x.Code = int32(code)
	if len(message) == 0 {
		x.Message = code.String()
	} else {
		x.Message = message
	}
}

func (x *CreateGreeterResponse) Reset() {
	*x = CreateGreeterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_greeter_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGreeterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGreeterResponse) ProtoMessage() {}

func (x *CreateGreeterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_greeter_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGreeterResponse.ProtoReflect.Descriptor instead.
func (*CreateGreeterResponse) Descriptor() ([]byte, []int) {
	return file_greeter_api_proto_rawDescGZIP(), []int{1}
}

func (x *CreateGreeterResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateGreeterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetGreeterByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
}

func (x *GetGreeterByIdRequest) Reset() {
	*x = GetGreeterByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_greeter_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGreeterByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGreeterByIdRequest) ProtoMessage() {}

func (x *GetGreeterByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_greeter_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGreeterByIdRequest.ProtoReflect.Descriptor instead.
func (*GetGreeterByIdRequest) Descriptor() ([]byte, []int) {
	return file_greeter_api_proto_rawDescGZIP(), []int{2}
}

func (x *GetGreeterByIdRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// @inject_response GetGreeterByIdResponse *Greeter data
type GetGreeterByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code"`
	Message string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	Data    *Greeter `protobuf:"bytes,3,opt,name=data,proto3" json:"data"`
}

// @inject_response GetGreeterByIdResponse *Greeter data
func (x *GetGreeterByIdResponse) SetCode(code status.Code, message string) {
	x.Code = int32(code)
	if len(message) == 0 {
		x.Message = code.String()
	} else {
		x.Message = message
	}
}

func (x *GetGreeterByIdResponse) SetBody(code status.Code, data *Greeter) {
	x.Code = int32(code)
	x.Message = code.String()
	x.Data = data
}

func (x *GetGreeterByIdResponse) Reset() {
	*x = GetGreeterByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_greeter_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGreeterByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGreeterByIdResponse) ProtoMessage() {}

func (x *GetGreeterByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_greeter_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGreeterByIdResponse.ProtoReflect.Descriptor instead.
func (*GetGreeterByIdResponse) Descriptor() ([]byte, []int) {
	return file_greeter_api_proto_rawDescGZIP(), []int{3}
}

func (x *GetGreeterByIdResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetGreeterByIdResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetGreeterByIdResponse) GetData() *Greeter {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetGreeterListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: validate:"gte=0,lte=3"
	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status" validate:"gte=0,lte=3"`
	Lastid int32 `protobuf:"varint,2,opt,name=lastid,proto3" json:"lastid"`
	// @inject_tag: validate:"gte=5,lte=20"
	Pagesize int32 `protobuf:"varint,3,opt,name=pagesize,proto3" json:"pagesize" validate:"gte=5,lte=20"`
	Page     int32 `protobuf:"varint,4,opt,name=page,proto3" json:"page"`
}

func (x *GetGreeterListRequest) Reset() {
	*x = GetGreeterListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_greeter_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGreeterListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGreeterListRequest) ProtoMessage() {}

func (x *GetGreeterListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_greeter_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGreeterListRequest.ProtoReflect.Descriptor instead.
func (*GetGreeterListRequest) Descriptor() ([]byte, []int) {
	return file_greeter_api_proto_rawDescGZIP(), []int{4}
}

func (x *GetGreeterListRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetGreeterListRequest) GetLastid() int32 {
	if x != nil {
		return x.Lastid
	}
	return 0
}

func (x *GetGreeterListRequest) GetPagesize() int32 {
	if x != nil {
		return x.Pagesize
	}
	return 0
}

func (x *GetGreeterListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

// @inject_response GetGreeterListResponse *GreeterList data
type GetGreeterListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32        `protobuf:"varint,1,opt,name=code,proto3" json:"code"`
	Message string       `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	Data    *GreeterList `protobuf:"bytes,3,opt,name=data,proto3" json:"data"`
}

// @inject_response GetGreeterListResponse *GreeterList data
func (x *GetGreeterListResponse) SetCode(code status.Code, message string) {
	x.Code = int32(code)
	if len(message) == 0 {
		x.Message = code.String()
	} else {
		x.Message = message
	}
}

func (x *GetGreeterListResponse) SetBody(code status.Code, data *GreeterList) {
	x.Code = int32(code)
	x.Message = code.String()
	x.Data = data
}

func (x *GetGreeterListResponse) Reset() {
	*x = GetGreeterListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_greeter_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGreeterListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGreeterListResponse) ProtoMessage() {}

func (x *GetGreeterListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_greeter_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGreeterListResponse.ProtoReflect.Descriptor instead.
func (*GetGreeterListResponse) Descriptor() ([]byte, []int) {
	return file_greeter_api_proto_rawDescGZIP(), []int{5}
}

func (x *GetGreeterListResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetGreeterListResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetGreeterListResponse) GetData() *GreeterList {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateGreeterStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Status int32 `protobuf:"varint,2,opt,name=status,proto3" json:"status"`
}

func (x *UpdateGreeterStatusRequest) Reset() {
	*x = UpdateGreeterStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_greeter_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateGreeterStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGreeterStatusRequest) ProtoMessage() {}

func (x *UpdateGreeterStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_greeter_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGreeterStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateGreeterStatusRequest) Descriptor() ([]byte, []int) {
	return file_greeter_api_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateGreeterStatusRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateGreeterStatusRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// @inject_response UpdateGreeterStatusResponse
type UpdateGreeterStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
}

// @inject_response UpdateGreeterStatusResponse
func (x *UpdateGreeterStatusResponse) SetCode(code status.Code, message string) {
	x.Code = int32(code)
	if len(message) == 0 {
		x.Message = code.String()
	} else {
		x.Message = message
	}
}

func (x *UpdateGreeterStatusResponse) Reset() {
	*x = UpdateGreeterStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_greeter_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateGreeterStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGreeterStatusResponse) ProtoMessage() {}

func (x *UpdateGreeterStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_greeter_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGreeterStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateGreeterStatusResponse) Descriptor() ([]byte, []int) {
	return file_greeter_api_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateGreeterStatusResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateGreeterStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateGreeterCountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Num    int32  `protobuf:"varint,2,opt,name=num,proto3" json:"num"`
	Column string `protobuf:"bytes,3,opt,name=column,proto3" json:"column"`
}

func (x *UpdateGreeterCountRequest) Reset() {
	*x = UpdateGreeterCountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_greeter_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateGreeterCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGreeterCountRequest) ProtoMessage() {}

func (x *UpdateGreeterCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_greeter_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGreeterCountRequest.ProtoReflect.Descriptor instead.
func (*UpdateGreeterCountRequest) Descriptor() ([]byte, []int) {
	return file_greeter_api_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateGreeterCountRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateGreeterCountRequest) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *UpdateGreeterCountRequest) GetColumn() string {
	if x != nil {
		return x.Column
	}
	return ""
}

// @inject_response UpdateGreeterCountResponse
type UpdateGreeterCountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
}

// @inject_response UpdateGreeterCountResponse
func (x *UpdateGreeterCountResponse) SetCode(code status.Code, message string) {
	x.Code = int32(code)
	if len(message) == 0 {
		x.Message = code.String()
	} else {
		x.Message = message
	}
}

func (x *UpdateGreeterCountResponse) Reset() {
	*x = UpdateGreeterCountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_greeter_api_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateGreeterCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGreeterCountResponse) ProtoMessage() {}

func (x *UpdateGreeterCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_greeter_api_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGreeterCountResponse.ProtoReflect.Descriptor instead.
func (*UpdateGreeterCountResponse) Descriptor() ([]byte, []int) {
	return file_greeter_api_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateGreeterCountResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateGreeterCountResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteGreeterByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
}

func (x *DeleteGreeterByIdRequest) Reset() {
	*x = DeleteGreeterByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_greeter_api_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteGreeterByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGreeterByIdRequest) ProtoMessage() {}

func (x *DeleteGreeterByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_greeter_api_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGreeterByIdRequest.ProtoReflect.Descriptor instead.
func (*DeleteGreeterByIdRequest) Descriptor() ([]byte, []int) {
	return file_greeter_api_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteGreeterByIdRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// @inject_response DeleteGreeterByIdResponse
type DeleteGreeterByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
}

// @inject_response DeleteGreeterByIdResponse
func (x *DeleteGreeterByIdResponse) SetCode(code status.Code, message string) {
	x.Code = int32(code)
	if len(message) == 0 {
		x.Message = code.String()
	} else {
		x.Message = message
	}
}

func (x *DeleteGreeterByIdResponse) Reset() {
	*x = DeleteGreeterByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_greeter_api_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteGreeterByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGreeterByIdResponse) ProtoMessage() {}

func (x *DeleteGreeterByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_greeter_api_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGreeterByIdResponse.ProtoReflect.Descriptor instead.
func (*DeleteGreeterByIdResponse) Descriptor() ([]byte, []int) {
	return file_greeter_api_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteGreeterByIdResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DeleteGreeterByIdResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Greeter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	// @inject_tag: validate:"required,email"
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name" validate:"required,email"`
	ViewNum int32  `protobuf:"varint,3,opt,name=view_num,json=viewNum,proto3" json:"view_num"`
	// @inject_tag: validate:"gte=0,lte=3"
	Status         int32  `protobuf:"varint,4,opt,name=status,proto3" json:"status" validate:"gte=0,lte=3"`
	CreateTime     int64  `protobuf:"varint,5,opt,name=create_time,json=createTime,proto3" json:"create_time"`
	CreateDatetime string `protobuf:"bytes,6,opt,name=create_datetime,json=createDatetime,proto3" json:"create_datetime"`
	UpdateDatetime string `protobuf:"bytes,7,opt,name=update_datetime,json=updateDatetime,proto3" json:"update_datetime"`
}

func (x *Greeter) Reset() {
	*x = Greeter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_greeter_api_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Greeter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Greeter) ProtoMessage() {}

func (x *Greeter) ProtoReflect() protoreflect.Message {
	mi := &file_greeter_api_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Greeter.ProtoReflect.Descriptor instead.
func (*Greeter) Descriptor() ([]byte, []int) {
	return file_greeter_api_proto_rawDescGZIP(), []int{12}
}

func (x *Greeter) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Greeter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Greeter) GetViewNum() int32 {
	if x != nil {
		return x.ViewNum
	}
	return 0
}

func (x *Greeter) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Greeter) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *Greeter) GetCreateDatetime() string {
	if x != nil {
		return x.CreateDatetime
	}
	return ""
}

func (x *Greeter) GetUpdateDatetime() string {
	if x != nil {
		return x.UpdateDatetime
	}
	return ""
}

type GreeterList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total     int32      `protobuf:"varint,1,opt,name=total,proto3" json:"total"`
	TotalPage int32      `protobuf:"varint,2,opt,name=total_page,json=totalPage,proto3" json:"total_page"`
	CurPage   int32      `protobuf:"varint,3,opt,name=cur_page,json=curPage,proto3" json:"cur_page"`
	Datalist  []*Greeter `protobuf:"bytes,4,rep,name=datalist,proto3" json:"datalist"`
}

func (x *GreeterList) Reset() {
	*x = GreeterList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_greeter_api_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GreeterList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreeterList) ProtoMessage() {}

func (x *GreeterList) ProtoReflect() protoreflect.Message {
	mi := &file_greeter_api_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreeterList.ProtoReflect.Descriptor instead.
func (*GreeterList) Descriptor() ([]byte, []int) {
	return file_greeter_api_proto_rawDescGZIP(), []int{13}
}

func (x *GreeterList) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GreeterList) GetTotalPage() int32 {
	if x != nil {
		return x.TotalPage
	}
	return 0
}

func (x *GreeterList) GetCurPage() int32 {
	if x != nil {
		return x.CurPage
	}
	return 0
}

func (x *GreeterList) GetDatalist() []*Greeter {
	if x != nil {
		return x.Datalist
	}
	return nil
}

type GetGreeterListByIdsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []int32 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids"`
}

func (x *GetGreeterListByIdsRequest) Reset() {
	*x = GetGreeterListByIdsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_greeter_api_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGreeterListByIdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGreeterListByIdsRequest) ProtoMessage() {}

func (x *GetGreeterListByIdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_greeter_api_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGreeterListByIdsRequest.ProtoReflect.Descriptor instead.
func (*GetGreeterListByIdsRequest) Descriptor() ([]byte, []int) {
	return file_greeter_api_proto_rawDescGZIP(), []int{14}
}

func (x *GetGreeterListByIdsRequest) GetIds() []int32 {
	if x != nil {
		return x.Ids
	}
	return nil
}

// @inject_response GetGreeterListByIdsResponse []*Greeter data
type GetGreeterListByIdsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32      `protobuf:"varint,1,opt,name=code,proto3" json:"code"`
	Message string     `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	Data    []*Greeter `protobuf:"bytes,3,rep,name=data,proto3" json:"data"`
}

// @inject_response GetGreeterListByIdsResponse []*Greeter data
func (x *GetGreeterListByIdsResponse) SetCode(code status.Code, message string) {
	x.Code = int32(code)
	if len(message) == 0 {
		x.Message = code.String()
	} else {
		x.Message = message
	}
}

func (x *GetGreeterListByIdsResponse) SetBody(code status.Code, data []*Greeter) {
	x.Code = int32(code)
	x.Message = code.String()
	x.Data = data
}

func (x *GetGreeterListByIdsResponse) Reset() {
	*x = GetGreeterListByIdsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_greeter_api_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGreeterListByIdsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGreeterListByIdsResponse) ProtoMessage() {}

func (x *GetGreeterListByIdsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_greeter_api_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGreeterListByIdsResponse.ProtoReflect.Descriptor instead.
func (*GetGreeterListByIdsResponse) Descriptor() ([]byte, []int) {
	return file_greeter_api_proto_rawDescGZIP(), []int{15}
}

func (x *GetGreeterListByIdsResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetGreeterListByIdsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetGreeterListByIdsResponse) GetData() []*Greeter {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_greeter_api_proto protoreflect.FileDescriptor

var file_greeter_api_proto_rawDesc = []byte{
	0x0a, 0x11, 0x67, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x2d, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x67, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x5f, 0x61, 0x70, 0x69,
	0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e,
	0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x40,
	0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x5f, 0x61,
	0x70, 0x69, 0x2e, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x22, 0x45, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x27, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x47, 0x72,
	0x65, 0x65, 0x74, 0x65, 0x72, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x70, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x42, 0x79,
	0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x28, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72,
	0x5f, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x77, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x61, 0x73, 0x74, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x6c, 0x61, 0x73, 0x74, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x61, 0x67, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70,
	0x61, 0x67, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x22, 0x74, 0x0a, 0x16, 0x47,
	0x65, 0x74, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x2c, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x5f, 0x61, 0x70, 0x69, 0x2e,
	0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x22, 0x44, 0x0a, 0x1a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x72, 0x65, 0x65, 0x74,
	0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x4b, 0x0a, 0x1b, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x22, 0x55, 0x0a, 0x19, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x72,
	0x65, 0x65, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x6e, 0x75, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x22, 0x4a, 0x0a, 0x1a, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x2a, 0x0a, 0x18, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x49, 0x0a, 0x19, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x72, 0x65,
	0x65, 0x74, 0x65, 0x72, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0xd3,
	0x01, 0x0a, 0x07, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x19,
	0x0a, 0x08, 0x76, 0x69, 0x65, 0x77, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x07, 0x76, 0x69, 0x65, 0x77, 0x4e, 0x75, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x64, 0x61, 0x74,
	0x65, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x65,
	0x74, 0x69, 0x6d, 0x65, 0x22, 0x8f, 0x01, 0x0a, 0x0b, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x61, 0x67, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x75, 0x72,
	0x5f, 0x70, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x63, 0x75, 0x72,
	0x50, 0x61, 0x67, 0x65, 0x12, 0x30, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x61, 0x6c, 0x69, 0x73, 0x74,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72,
	0x5f, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x52, 0x08, 0x64, 0x61,
	0x74, 0x61, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x2e, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x47, 0x72, 0x65,
	0x65, 0x74, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x79, 0x49, 0x64, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x05, 0x52, 0x03, 0x69, 0x64, 0x73, 0x22, 0x75, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x47, 0x72, 0x65,
	0x65, 0x74, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x79, 0x49, 0x64, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x28, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x5f, 0x61, 0x70, 0x69, 0x2e,
	0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0x95, 0x07,
	0x0a, 0x0e, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x75, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65,
	0x72, 0x12, 0x21, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x5f, 0x61, 0x70, 0x69, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x5f, 0x61,
	0x70, 0x69, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1d, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x17,
	0x22, 0x12, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x2f, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x3a, 0x01, 0x2a, 0x12, 0x77, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x47, 0x72,
	0x65, 0x65, 0x74, 0x65, 0x72, 0x42, 0x79, 0x49, 0x64, 0x12, 0x22, 0x2e, 0x67, 0x72, 0x65, 0x65,
	0x74, 0x65, 0x72, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x72, 0x65, 0x65, 0x74,
	0x65, 0x72, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e,
	0x67, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x47,
	0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x1c, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x16, 0x12, 0x14, 0x2f, 0x76, 0x31, 0x2f,
	0x67, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x2f, 0x6f, 0x6e, 0x65, 0x2f, 0x7b, 0x69, 0x64, 0x7d,
	0x12, 0x7c, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x22, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x5f, 0x61, 0x70, 0x69,
	0x2e, 0x47, 0x65, 0x74, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72,
	0x5f, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x21, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x1b, 0x12, 0x19, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72,
	0x2f, 0x6c, 0x69, 0x73, 0x74, 0x2f, 0x7b, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x7d, 0x12, 0x87,
	0x01, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x27, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72,
	0x5f, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x72, 0x65, 0x65, 0x74,
	0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x28, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1d, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x17, 0x22, 0x12, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x2f, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x3a, 0x01, 0x2a, 0x12, 0x83, 0x01, 0x0a, 0x12, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x26, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x65,
	0x72, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x72, 0x65, 0x65,
	0x74, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x1c, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x16, 0x22, 0x11, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x72,
	0x65, 0x65, 0x74, 0x65, 0x72, 0x2f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x3a, 0x01, 0x2a, 0x12, 0x7e,
	0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x42,
	0x79, 0x49, 0x64, 0x12, 0x25, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x5f, 0x61, 0x70,
	0x69, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x42,
	0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x67, 0x72, 0x65,
	0x65, 0x74, 0x65, 0x72, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47,
	0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x1a, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x14, 0x22, 0x0f, 0x2f, 0x76, 0x31, 0x2f,
	0x67, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x2f, 0x64, 0x65, 0x6c, 0x3a, 0x01, 0x2a, 0x12, 0x84,
	0x01, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x4c, 0x69, 0x73,
	0x74, 0x42, 0x79, 0x49, 0x64, 0x73, 0x12, 0x27, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72,
	0x5f, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x4c,
	0x69, 0x73, 0x74, 0x42, 0x79, 0x49, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x28, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65,
	0x74, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x79, 0x49, 0x64,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1a, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x14, 0x22, 0x0f, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x2f, 0x69,
	0x64, 0x73, 0x3a, 0x01, 0x2a, 0x42, 0x4c, 0x5a, 0x4a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x6d, 0x69, 0x6e, 0x64, 0x2d, 0x6c, 0x61, 0x62, 0x2f, 0x67, 0x72,
	0x65, 0x65, 0x74, 0x65, 0x72, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x67, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x2d, 0x61, 0x70,
	0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x67, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x5f,
	0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_greeter_api_proto_rawDescOnce sync.Once
	file_greeter_api_proto_rawDescData = file_greeter_api_proto_rawDesc
)

func file_greeter_api_proto_rawDescGZIP() []byte {
	file_greeter_api_proto_rawDescOnce.Do(func() {
		file_greeter_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_greeter_api_proto_rawDescData)
	})
	return file_greeter_api_proto_rawDescData
}

var file_greeter_api_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_greeter_api_proto_goTypes = []interface{}{
	(*CreateGreeterRequest)(nil),        // 0: greeter_api.CreateGreeterRequest
	(*CreateGreeterResponse)(nil),       // 1: greeter_api.CreateGreeterResponse
	(*GetGreeterByIdRequest)(nil),       // 2: greeter_api.GetGreeterByIdRequest
	(*GetGreeterByIdResponse)(nil),      // 3: greeter_api.GetGreeterByIdResponse
	(*GetGreeterListRequest)(nil),       // 4: greeter_api.GetGreeterListRequest
	(*GetGreeterListResponse)(nil),      // 5: greeter_api.GetGreeterListResponse
	(*UpdateGreeterStatusRequest)(nil),  // 6: greeter_api.UpdateGreeterStatusRequest
	(*UpdateGreeterStatusResponse)(nil), // 7: greeter_api.UpdateGreeterStatusResponse
	(*UpdateGreeterCountRequest)(nil),   // 8: greeter_api.UpdateGreeterCountRequest
	(*UpdateGreeterCountResponse)(nil),  // 9: greeter_api.UpdateGreeterCountResponse
	(*DeleteGreeterByIdRequest)(nil),    // 10: greeter_api.DeleteGreeterByIdRequest
	(*DeleteGreeterByIdResponse)(nil),   // 11: greeter_api.DeleteGreeterByIdResponse
	(*Greeter)(nil),                     // 12: greeter_api.Greeter
	(*GreeterList)(nil),                 // 13: greeter_api.GreeterList
	(*GetGreeterListByIdsRequest)(nil),  // 14: greeter_api.GetGreeterListByIdsRequest
	(*GetGreeterListByIdsResponse)(nil), // 15: greeter_api.GetGreeterListByIdsResponse
}
var file_greeter_api_proto_depIdxs = []int32{
	12, // 0: greeter_api.CreateGreeterRequest.data:type_name -> greeter_api.Greeter
	12, // 1: greeter_api.GetGreeterByIdResponse.data:type_name -> greeter_api.Greeter
	13, // 2: greeter_api.GetGreeterListResponse.data:type_name -> greeter_api.GreeterList
	12, // 3: greeter_api.GreeterList.datalist:type_name -> greeter_api.Greeter
	12, // 4: greeter_api.GetGreeterListByIdsResponse.data:type_name -> greeter_api.Greeter
	0,  // 5: greeter_api.GreeterService.CreateGreeter:input_type -> greeter_api.CreateGreeterRequest
	2,  // 6: greeter_api.GreeterService.GetGreeterById:input_type -> greeter_api.GetGreeterByIdRequest
	4,  // 7: greeter_api.GreeterService.GetGreeterList:input_type -> greeter_api.GetGreeterListRequest
	6,  // 8: greeter_api.GreeterService.UpdateGreeterStatus:input_type -> greeter_api.UpdateGreeterStatusRequest
	8,  // 9: greeter_api.GreeterService.UpdateGreeterCount:input_type -> greeter_api.UpdateGreeterCountRequest
	10, // 10: greeter_api.GreeterService.DeleteGreeterById:input_type -> greeter_api.DeleteGreeterByIdRequest
	14, // 11: greeter_api.GreeterService.GetGreeterListByIds:input_type -> greeter_api.GetGreeterListByIdsRequest
	1,  // 12: greeter_api.GreeterService.CreateGreeter:output_type -> greeter_api.CreateGreeterResponse
	3,  // 13: greeter_api.GreeterService.GetGreeterById:output_type -> greeter_api.GetGreeterByIdResponse
	5,  // 14: greeter_api.GreeterService.GetGreeterList:output_type -> greeter_api.GetGreeterListResponse
	7,  // 15: greeter_api.GreeterService.UpdateGreeterStatus:output_type -> greeter_api.UpdateGreeterStatusResponse
	9,  // 16: greeter_api.GreeterService.UpdateGreeterCount:output_type -> greeter_api.UpdateGreeterCountResponse
	11, // 17: greeter_api.GreeterService.DeleteGreeterById:output_type -> greeter_api.DeleteGreeterByIdResponse
	15, // 18: greeter_api.GreeterService.GetGreeterListByIds:output_type -> greeter_api.GetGreeterListByIdsResponse
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_greeter_api_proto_init() }
func file_greeter_api_proto_init() {
	if File_greeter_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_greeter_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateGreeterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_greeter_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateGreeterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_greeter_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGreeterByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_greeter_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGreeterByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_greeter_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGreeterListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_greeter_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGreeterListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_greeter_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateGreeterStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_greeter_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateGreeterStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_greeter_api_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateGreeterCountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_greeter_api_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateGreeterCountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_greeter_api_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteGreeterByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_greeter_api_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteGreeterByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_greeter_api_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Greeter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_greeter_api_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GreeterList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_greeter_api_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGreeterListByIdsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_greeter_api_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGreeterListByIdsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_greeter_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_greeter_api_proto_goTypes,
		DependencyIndexes: file_greeter_api_proto_depIdxs,
		MessageInfos:      file_greeter_api_proto_msgTypes,
	}.Build()
	File_greeter_api_proto = out.File
	file_greeter_api_proto_rawDesc = nil
	file_greeter_api_proto_goTypes = nil
	file_greeter_api_proto_depIdxs = nil
}
