{{- if .Values.traefik.enabled -}}
{{- $fullName := include "imind.fullname" . -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "imind.labels" . | nindent 4 }}
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`{{ .Values.traefik.http.host }}`)
      kind: Rule
      services:
        - name: {{ $fullName }}
          port: {{ .Values.traefik.http.port }}

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}-grpc
  labels:
    {{- include "imind.labels" . | nindent 4 }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.traefik.grpc.host }}`)
      kind: Rule
      services:
        - name: {{ $fullName }}
          port: {{ .Values.traefik.grpc.port }}
          kind: Service
          scheme: https
  tls:
    secretName: {{ .Values.traefik.grpc.tls }}
{{- end }}
