{{- $fullName := include "imind.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "imind.labels" . | nindent 4 }}
type: Opaque
data:
  {{ (.Files.Glob "conf/conf.yaml").AsSecrets | indent 2 }}
